# Generated by Django 5.2.4 on 2025-09-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicecaption',
            name='modality',
            field=models.CharField(default='ios', help_text='Modality slug (e.g., ios, cbct, or any from common.Modality)', max_length=255),
        ),
    ]
