# Generated by Django 5.2.4

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maxillo', '0003_add_project_manager_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('query_params', models.JSONField(default=dict, help_text='Stores folder_ids, modality_slugs, and filters')),
                ('query_summary', models.CharField(blank=True, help_text='Human-readable query summary', max_length=500)),
                ('file_path', models.CharField(blank=True, help_text='Path to generated ZIP file', max_length=1000)),
                ('file_size', models.BigIntegerField(default=0, help_text='Size of export file in bytes')),
                ('patient_count', models.IntegerField(default=0, help_text='Number of patients in export')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When processing started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When processing completed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if export failed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scans_export',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='export',
            index=models.Index(fields=['user', 'status'], name='scans_expor_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='export',
            index=models.Index(fields=['status', 'created_at'], name='scans_expor_status_idx'),
        ),
    ]
