# Generated by Django 5.2.4 on 2025-12-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0004_maxillouserprofile_delete_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maxillouserprofile',
            options={'verbose_name': 'User profile', 'verbose_name_plural': 'User profiles'},
        ),
    ]
