# Generated by Django 5.2.4 on 2026-01-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0004_export'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='export',
            new_name='scans_expor_user_id_a7d988_idx',
            old_name='scans_expor_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='export',
            new_name='scans_expor_status_56a6c3_idx',
            old_name='scans_expor_status_idx',
        ),
    ]
