# Generated by Django 5.2.4 on 2026-01-27

from django.db import migrations


class Migration(migrations.Migration):
    """
    Merge migration to resolve parallel migration paths:
    - 0004_export -> 0005_rename_scans_expor...
    - 0004_maxillouserprofile_delete_userprofile -> 0005_alter_maxillouserprofile_options
    """

    dependencies = [
        ('maxillo', '0005_alter_maxillouserprofile_options'),
        ('maxillo', '0005_rename_scans_expor_user_id_idx_scans_expor_user_id_a7d988_idx_and_more'),
    ]

    operations = [
    ]
