# Generated by Django 5.2.4 on 2026-01-27 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxillo', '0006_merge_20260127'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='classification',
            new_name='maxillo_cla_patient_219324_idx',
            old_name='scans_class_patient_c507dc_idx',
        ),
        migrations.RenameIndex(
            model_name='classification',
            new_name='maxillo_cla_classif_fb49dd_idx',
            old_name='scans_class_classif_fc1966_idx',
        ),
        migrations.RenameIndex(
            model_name='folder',
            new_name='maxillo_fol_parent__3d9822_idx',
            old_name='scans_folde_parent__9b2827_idx',
        ),
        migrations.RenameIndex(
            model_name='folder',
            new_name='maxillo_fol_name_fe24d2_idx',
            old_name='scans_folde_name_7a86ed_idx',
        ),
        migrations.RenameIndex(
            model_name='patient',
            new_name='maxillo_pat_project_30b5f2_idx',
            old_name='scans_patie_project_18f4e1_idx',
        ),
        migrations.RenameIndex(
            model_name='patient',
            new_name='maxillo_pat_visibil_f2fe49_idx',
            old_name='scans_patie_visibil_a7bf65_idx',
        ),
        migrations.RenameIndex(
            model_name='patient',
            new_name='maxillo_pat_uploade_d08326_idx',
            old_name='scans_patie_uploade_2e9c22_idx',
        ),
        migrations.RenameIndex(
            model_name='patient',
            new_name='maxillo_pat_folder__4ebd19_idx',
            old_name='scans_patie_folder__c2aeae_idx',
        ),
        migrations.RenameIndex(
            model_name='patient',
            new_name='maxillo_pat_name_fb819f_idx',
            old_name='scans_patie_name_ca8447_idx',
        ),
        migrations.RenameIndex(
            model_name='patient',
            new_name='maxillo_pat_project_d7f0f3_idx',
            old_name='scans_patie_project_84fea6_idx',
        ),
        migrations.RenameIndex(
            model_name='patient',
            new_name='maxillo_pat_project_e2cf6d_idx',
            old_name='scans_patie_project_427bf6_idx',
        ),
        migrations.RenameIndex(
            model_name='patient',
            new_name='maxillo_pat_visibil_9cc31e_idx',
            old_name='scans_patie_visibil_926fa7_idx',
        ),
        migrations.RenameIndex(
            model_name='patient',
            new_name='maxillo_pat_folder__6865fa_idx',
            old_name='scans_patie_folder__b4f37a_idx',
        ),
        migrations.RenameIndex(
            model_name='patient',
            new_name='maxillo_pat_project_d498c7_idx',
            old_name='scans_patie_project_3e6f9f_idx',
        ),
        migrations.RenameIndex(
            model_name='tag',
            new_name='maxillo_tag_name_c46ae6_idx',
            old_name='scans_tag_name_d48e7d_idx',
        ),
        migrations.RenameIndex(
            model_name='voicecaption',
            new_name='maxillo_voi_patient_8431b4_idx',
            old_name='scans_voice_patient_a95f98_idx',
        ),
        migrations.RenameIndex(
            model_name='voicecaption',
            new_name='maxillo_voi_process_e47dee_idx',
            old_name='scans_voice_process_cea49d_idx',
        ),
        migrations.RenameIndex(
            model_name='voicecaption',
            new_name='maxillo_voi_user_id_ec2d5c_idx',
            old_name='scans_voice_user_id_d7afd5_idx',
        ),
        migrations.AlterField(
            model_name='classification',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='maxillo.patient'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='maxillo.folder'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='maxillo.dataset'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='maxillo.folder'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='patients', to='maxillo.tag'),
        ),
        migrations.AlterField(
            model_name='voicecaption',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_captions', to='maxillo.patient'),
        ),
    ]
