# Generated by Django 5.2.4 on 2026-01-27
from django.db import migrations


class Migration(migrations.Migration):
    """
    Safe deletion of MaxilloUserProfile model.
    Uses SeparateDatabaseAndState to handle the migration in two phases:
    1. State operation: Tell Django the model no longer exists
    2. Database operation: Actually drop the table

    This approach is safe for rolling deployments where old code might
    still be running during the migration.
    """
    dependencies = [
        ('maxillo', '0007_rename_scans_class_patient_c507dc_idx_maxillo_cla_patient_219324_idx_and_more'),
        ('common', '0017_remove_projectaccess_booleans'),  # Ensure cleanup happens after refactoring
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='MaxilloUserProfile'),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS maxillo_maxillouserprofile;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
