# Generated by Django 5.2.4 on 2026-01-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxillo', '0008_delete_maxillouserprofile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='export',
            new_name='maxillo_exp_user_id_2532ea_idx',
            old_name='scans_expor_user_id_a7d988_idx',
        ),
        migrations.RenameIndex(
            model_name='export',
            new_name='maxillo_exp_status_e90e7b_idx',
            old_name='scans_expor_status_56a6c3_idx',
        ),
        migrations.AlterModelTable(
            name='export',
            table='maxillo_export',
        ),
    ]
