# Generated by Django 5.2.4 on 2026-03-30 17:39

from django.db import migrations, models


def add_export_progress_columns(apps, schema_editor):
    table_name = 'maxillo_export'
    with schema_editor.connection.cursor() as cursor:
        columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }

    if 'progress_message' not in columns:
        schema_editor.execute(
            "ALTER TABLE maxillo_export ADD COLUMN progress_message VARCHAR(255) NOT NULL DEFAULT ''"
        )

    if 'progress_percent' not in columns:
        schema_editor.execute(
            'ALTER TABLE maxillo_export ADD COLUMN progress_percent INTEGER NULL'
        )


def remove_export_progress_columns(apps, schema_editor):
    table_name = 'maxillo_export'
    with schema_editor.connection.cursor() as cursor:
        columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }

    if 'progress_message' in columns:
        schema_editor.execute('ALTER TABLE maxillo_export DROP COLUMN progress_message')

    if 'progress_percent' in columns:
        schema_editor.execute('ALTER TABLE maxillo_export DROP COLUMN progress_percent')


class Migration(migrations.Migration):

    dependencies = [
        ('maxillo', '0009_rename_scans_expor_user_id_a7d988_idx_maxillo_exp_user_id_2532ea_idx_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_export_progress_columns, remove_export_progress_columns),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='export',
                    name='progress_message',
                    field=models.CharField(blank=True, help_text='Current phase or progress text', max_length=255),
                ),
                migrations.AddField(
                    model_name='export',
                    name='progress_percent',
                    field=models.IntegerField(blank=True, help_text='Progress 0-100', null=True),
                ),
            ],
        ),
    ]
