# Generated by Django 5.2.4 on 2026-03-31 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxillo', '0012_drop_patient_project'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='patient',
                    name='maxillo_pat_project_30b5f2_idx',
                ),
                migrations.RemoveIndex(
                    model_name='patient',
                    name='maxillo_pat_project_d7f0f3_idx',
                ),
                migrations.RemoveIndex(
                    model_name='patient',
                    name='maxillo_pat_project_e2cf6d_idx',
                ),
                migrations.RemoveIndex(
                    model_name='patient',
                    name='maxillo_pat_project_d498c7_idx',
                ),
            ],
        ),
    ]
