# Generated by Django 5.2.4 on 2026-04-17 13:18

import django.db.models.deletion
from django.db import migrations, models


def assign_maxillo_project(apps, schema_editor):
    Patient = apps.get_model('maxillo', 'Patient')
    Project = apps.get_model('common', 'Project')
    maxillo_proj = Project.objects.filter(slug='maxillo').first()
    if maxillo_proj:
        Patient.objects.filter(project__isnull=True).update(project=maxillo_proj)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_alter_fileregistry_file_type'),
        ('maxillo', '0015_export_sharing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='common.project'),
        ),
        migrations.RunPython(assign_maxillo_project, migrations.RunPython.noop),
    ]
