# Generated by Django 5.2.4 on 2025-09-04 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('scans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fileregistry',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='scans.patient'),
        ),
        migrations.AddField(
            model_name='fileregistry',
            name='voice_caption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='scans.voicecaption'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='used_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invitation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modality',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='dependencies',
            field=models.ManyToManyField(blank=True, help_text='Jobs that must complete before this job can start', related_name='dependent_jobs', to='common.processingjob'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='scans.patient'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='voice_caption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='scans.voicecaption'),
        ),
        migrations.AddField(
            model_name='fileregistry',
            name='processing_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='common.processingjob'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='modalities',
            field=models.ManyToManyField(blank=True, related_name='projects', to='common.modality'),
        ),
        migrations.AddField(
            model_name='projectaccess',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_list', to='common.project'),
        ),
        migrations.AddField(
            model_name='projectaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['job_type', 'status'], name='scans_proce_job_typ_0a4f26_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['status', 'created_at'], name='scans_proce_status_470d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='fileregistry',
            index=models.Index(fields=['file_type', 'patient'], name='scans_filer_file_ty_a92f05_idx'),
        ),
        migrations.AddIndex(
            model_name='fileregistry',
            index=models.Index(fields=['file_path'], name='scans_filer_file_pa_856bfb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectaccess',
            unique_together={('user', 'project')},
        ),
    ]
