# Generated by Django 5.2.4 on 2025-09-04 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_job_alter_fileregistry_processing_job_and_more'),
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileregistry',
            name='modality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='common.modality'),
        ),
        migrations.AddField(
            model_name='fileregistry',
            name='subtype',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='modality',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='modality',
            name='subtypes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='fileregistry',
            index=models.Index(fields=['modality', 'patient'], name='scans_filer_modalit_6b1da1_idx'),
        ),
        migrations.AddIndex(
            model_name='fileregistry',
            index=models.Index(fields=['modality', 'subtype', 'patient'], name='scans_filer_modalit_d0e01a_idx'),
        ),
    ]
