# Generated by Django 5.2.4 on 2025-09-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_fileregistry_modality_fileregistry_subtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modality',
            name='label',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
