# Generated by Django 5.2.4 on 2025-10-28 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_add_job_patient_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Optional: Project the user will have access to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='common.project'),
        ),
    ]
