# Generated by Django 5.2.4 on 2025-12-02 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_invitation_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='project',
            field=models.ForeignKey(
                on_delete=models.SET_NULL,    
                to='common.project',
                null=True,
                blank=True,
                related_name='invitations',
                help_text='Project the user will have access to',
            ),
            preserve_default=False,
        ),
    ]
