# Generated by Django 5.2.4 on 2025-12-02 16:11

import django.db.models.deletion
from django.db import migrations, models


def set_default_project(apps, schema_editor):
    Invitation = apps.get_model('common', 'Invitation')
    Project = apps.get_model('common', 'Project')

    default_project = Project.objects.get(slug='maxillo')

    # Assign default project to all invitations that have no project yet
    Invitation.objects.filter(project__isnull=True).update(project=default_project)

def unset_default_project(apps, schema_editor):
    # Reverse function: in case of migration rollback
    Invitation = apps.get_model('common', 'Invitation')
    # You can either set project back to NULL:
    Invitation.objects.filter().update(project=None)
    # or leave it empty if you don't care about rolling back

class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_invitation_project'),
    ]

    operations = [
        migrations.RunPython(set_default_project, unset_default_project),
    ]
