# Generated by Django 5.2.4 on 2025-12-03 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_alter_invitation_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='project',
            field=models.ForeignKey(help_text='Project the user will have access to', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='common.project'),
        ),
    ]
