# Generated by Django 5.2.4 on 2026-01-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_alter_invitation_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectaccess',
            name='role',
            field=models.CharField(choices=[('standard', 'Standard User'), ('annotator', 'Annotator'), ('project_manager', 'Project Manager'), ('admin', 'Administrator'), ('student_dev', 'Student Developer')], default='standard', max_length=20),
        ),
    ]
