# Generated by Django 5.2.4 on 2026-01-27
from django.db import migrations


class Migration(migrations.Migration):
    """
    Remove deprecated boolean fields from ProjectAccess.
    The role field is now the single source of truth for permissions.
    """

    dependencies = [
        ('common', '0016_migrate_profile_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectaccess',
            name='can_view',
        ),
        migrations.RemoveField(
            model_name='projectaccess',
            name='can_upload',
        ),
    ]
