# Generated by Django 5.2.4 on 2026-01-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_remove_projectaccess_booleans'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fileregistry',
            new_name='maxillo_fil_file_ty_9e6e6a_idx',
            old_name='scans_filer_file_ty_a92f05_idx',
        ),
        migrations.RenameIndex(
            model_name='fileregistry',
            new_name='maxillo_fil_modalit_ab9177_idx',
            old_name='scans_filer_modalit_6b1da1_idx',
        ),
        migrations.RenameIndex(
            model_name='fileregistry',
            new_name='maxillo_fil_modalit_dd5990_idx',
            old_name='scans_filer_modalit_d0e01a_idx',
        ),
        migrations.RenameIndex(
            model_name='fileregistry',
            new_name='maxillo_fil_file_pa_31a4c2_idx',
            old_name='scans_filer_file_pa_856bfb_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='maxillo_job_modalit_329116_idx',
            old_name='scans_job_modalit_f8675b_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='maxillo_job_status_e12c48_idx',
            old_name='scans_job_status_7dcbd0_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='maxillo_job_patient_38f476_idx',
            old_name='scans_job_patient_edf126_idx',
        ),
        migrations.RenameIndex(
            model_name='processingjob',
            new_name='maxillo_pro_job_typ_af1ff2_idx',
            old_name='scans_proce_job_typ_0a4f26_idx',
        ),
        migrations.RenameIndex(
            model_name='processingjob',
            new_name='maxillo_pro_status_70d04b_idx',
            old_name='scans_proce_status_470d4b_idx',
        ),
        migrations.AlterModelTable(
            name='fileregistry',
            table='maxillo_fileregistry',
        ),
        migrations.AlterModelTable(
            name='invitation',
            table='maxillo_invitation',
        ),
        migrations.AlterModelTable(
            name='job',
            table='maxillo_job',
        ),
        migrations.AlterModelTable(
            name='processingjob',
            table='maxillo_processingjob',
        ),
    ]
