# Generated by Django 5.2.4 on 2026-03-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_rename_scans_filer_file_ty_a92f05_idx_maxillo_fil_file_ty_9e6e6a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='email_send_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
