# Generated by Django 5.2.4 on 2026-03-30 00:00

from django.db import migrations, models


def copy_project_fk_to_m2m(apps, schema_editor):
    Invitation = apps.get_model('common', 'Invitation')
    for invitation in Invitation.objects.select_related('project').all():
        if invitation.project_id:
            invitation.projects.add(invitation.project_id)


def reverse_copy_project_fk_to_m2m(apps, schema_editor):
    Invitation = apps.get_model('common', 'Invitation')
    for invitation in Invitation.objects.prefetch_related('projects').all():
        first_project = invitation.projects.first()
        if first_project:
            invitation.project_id = first_project.id
            invitation.save(update_fields=['project'])


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_invitation_email_delivery_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='projects',
            field=models.ManyToManyField(help_text='Projects the user will have access to', related_name='invitations_multi', to='common.project'),
        ),
        migrations.RunPython(copy_project_fk_to_m2m, reverse_copy_project_fk_to_m2m),
    ]
