# Generated by Django 5.2.4 on 2026-03-31 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_backfill_brain_domain_links'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fileregistry',
            new_name='maxillo_fil_domain_760eb4_idx',
            old_name='common_file_domain_22309d_idx',
        ),
        migrations.RenameIndex(
            model_name='fileregistry',
            new_name='maxillo_fil_domain_c156db_idx',
            old_name='common_file_domain_2ca253_idx',
        ),
        migrations.RenameIndex(
            model_name='fileregistry',
            new_name='maxillo_fil_domain_0575c1_idx',
            old_name='common_file_domain_a21df0_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='maxillo_job_domain_9f1efe_idx',
            old_name='common_job_domain_24ebf4_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='maxillo_job_domain_ea6d13_idx',
            old_name='common_job_domain_82fd40_idx',
        ),
        migrations.RenameIndex(
            model_name='processingjob',
            new_name='maxillo_pro_domain_8b0dc0_idx',
            old_name='common_proc_domain_4734bf_idx',
        ),
        migrations.RenameIndex(
            model_name='processingjob',
            new_name='maxillo_pro_domain_9694e0_idx',
            old_name='common_proc_domain_8264b6_idx',
        ),
    ]
