# Generated by Django 5.2.4 on 2026-01-27
from django.db import migrations


class Migration(migrations.Migration):
    """
    Safe deletion of BrainUserProfile model.
    Uses SeparateDatabaseAndState to handle the migration in two phases.
    """
    dependencies = [
        ('brain', '0002_alter_brainuserprofile_options'),
        ('common', '0017_remove_projectaccess_booleans'),  # Ensure cleanup happens after refactoring
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='BrainUserProfile'),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS brain_brainuserprofile;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
