# Generated by Django 5.2.4 on 2026-04-15 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laparoscopy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuadrantTypeUserColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
                ('quadrant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_colors', to='laparoscopy.quadranttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laparoscopy_quadrant_colors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('quadrant_type', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RegionTypeUserColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
                ('region_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_colors', to='laparoscopy.regiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laparoscopy_region_colors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('region_type', 'user')},
            },
        ),
    ]
