# Generated by Django 5.2.4 on 2026-04-15 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laparoscopy', '0002_quadranttypeusercolor_regiontypeusercolor'),
        ('maxillo', '0015_export_sharing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(choices=[('brush', 'Brush'), ('eraser', 'Eraser'), ('polygon', 'Polygon')], max_length=20)),
                ('frame_time', models.FloatField(default=0.0)),
                ('points', models.JSONField(default=list)),
                ('stroke_width', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_laparoscopy_annotations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laparoscopy_region_annotations', to='maxillo.patient')),
                ('region_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='laparoscopy.regiontype')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_laparoscopy_annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegionAnnotationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update_geometry', 'Update geometry'), ('change_region', 'Change region'), ('delete', 'Delete')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='laparoscopy.regionannotation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laparoscopy_region_annotation_actions', to='maxillo.patient')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laparoscopy_region_annotation_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='regionannotation',
            index=models.Index(fields=['patient', 'frame_time'], name='laparoscopy_patient_f56b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='regionannotation',
            index=models.Index(fields=['patient', 'region_type'], name='laparoscopy_patient_728243_idx'),
        ),
        migrations.AddIndex(
            model_name='regionannotation',
            index=models.Index(fields=['created_by'], name='laparoscopy_created_8f1b39_idx'),
        ),
        migrations.AddIndex(
            model_name='regionannotationaction',
            index=models.Index(fields=['patient', 'created_at'], name='laparoscopy_patient_44898f_idx'),
        ),
        migrations.AddIndex(
            model_name='regionannotationaction',
            index=models.Index(fields=['action_type', 'created_at'], name='laparoscopy_action__53c3d2_idx'),
        ),
    ]
