# Generated by Django 5.2.4 on 2026-04-15 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laparoscopy', '0003_regionannotation_regionannotationaction_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegionAnnotationAction',
        ),
    ]
