# Generated by Django 5.2.4 on 2026-04-15 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laparoscopy', '0004_delete_regionannotationaction'),
        ('maxillo', '0015_export_sharing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuadrantClassificationMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_laparoscopy_quadrant_markers', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laparoscopy_quadrant_markers', to='maxillo.patient')),
                ('quadrant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='laparoscopy.quadranttype')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_laparoscopy_quadrant_markers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time_ms', 'id'],
                'indexes': [models.Index(fields=['patient', 'time_ms'], name='laparoscopy_patient_e98295_idx'), models.Index(fields=['patient', 'quadrant_type'], name='laparoscopy_patient_0b0895_idx')],
                'constraints': [models.UniqueConstraint(fields=('patient', 'time_ms'), name='laparo_unique_patient_quadrant_marker_time')],
            },
        ),
    ]
