# Generated by Django 5.2.4 on 2026-04-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laparoscopy', '0005_quadrantclassificationmarker'),
        ('maxillo', '0016_patient_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaparoscopyPatient',
            fields=[
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('maxillo.patient',),
        ),
    ]
