# Generated by Django 5.2.4 on 2025-07-26 14:29

import django.core.validators
import django.db.models.deletion
import scans.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScanPair",
            fields=[
                ("scanpair_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "upper_scan_raw",
                    models.FileField(
                        upload_to=scans.models.scan_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["stl"]
                            )
                        ],
                    ),
                ),
                (
                    "lower_scan_raw",
                    models.FileField(
                        upload_to=scans.models.scan_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["stl"]
                            )
                        ],
                    ),
                ),
                (
                    "upper_scan_norm",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=scans.models.normalized_scan_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["stl"]
                            )
                        ],
                    ),
                ),
                (
                    "lower_scan_norm",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=scans.models.normalized_scan_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["stl"]
                            )
                        ],
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="private",
                        max_length=10,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_pairs",
                        to="scans.patient",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classifier",
                    models.CharField(
                        choices=[("manual", "Manual"), ("pipeline", "Pipeline")],
                        max_length=10,
                    ),
                ),
                (
                    "sagittal_left",
                    models.CharField(
                        choices=[
                            ("I", "Class I"),
                            ("II_edge", "Class II Edge"),
                            ("II_full", "Class II Full"),
                            ("III", "Class III"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "sagittal_right",
                    models.CharField(
                        choices=[
                            ("I", "Class I"),
                            ("II_edge", "Class II Edge"),
                            ("II_full", "Class II Full"),
                            ("III", "Class III"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "vertical",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("deep", "Deep Bite"),
                            ("reverse", "Reverse Bite"),
                            ("open", "Open Bite"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "transverse",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("cross", "Cross Bite"),
                            ("scissor", "Scissor Bite"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "midline",
                    models.CharField(
                        choices=[("centered", "Centered"), ("deviated", "Deviated")],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "annotator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scanpair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classifications",
                        to="scans.scanpair",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("standard", "Standard User"),
                            ("annotator", "Annotator"),
                            ("admin", "Administrator"),
                        ],
                        default="standard",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
