# Generated by Django 5.2.4 on 2025-07-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_dataset_scanpair_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanpair',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
