# Generated by Django 5.2.4 on 2025-07-28 15:08

import django.core.validators
import scans.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0004_scanpair_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanpair',
            name='cbct',
            field=models.FileField(blank=True, null=True, upload_to=scans.models.cbct_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gz'])]),
        ),
    ]
