# Generated by Django 5.2.4 on 2025-07-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_add_cbct_field'),
        ('scans', '0005_add_processing_status'),
    ]

    operations = [
    ]
