# Generated by Django 5.2.4 on 2025-07-30 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0006_add_voice_caption'),
        ('scans', '0006_merge_0005_add_cbct_field_0005_add_processing_status'),
    ]

    operations = [
    ]
