# Generated by Django 5.2.4 on 2025-07-30 08:10

import django.core.validators
import scans.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0007_merge_20250730_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanpair',
            name='cbct',
            field=models.FileField(blank=True, null=True, upload_to=scans.models.cbct_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['nii', 'gz'])]),
        ),
    ]
