# Generated by Django 5.2.4 on 2025-07-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0008_alter_scanpair_cbct'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicecaption',
            name='modality',
            field=models.CharField(choices=[('ios', 'Intra-Oral Scans'), ('cbct', 'CBCT')], default='ios', help_text='Whether this caption describes IOS or CBCT scans', max_length=10),
        ),
    ]
