# Generated by Django 5.2.4 on 2025-07-30 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0009_voicecaption_modality'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('cbct', 'CBCT Processing'), ('ios', 'IOS Processing'), ('audio', 'Audio Speech-to-Text')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Higher values = higher priority')),
                ('input_file_path', models.CharField(help_text='Path to input file in /dataset', max_length=500)),
                ('output_files', models.JSONField(blank=True, default=dict, help_text='Dict of output file paths and metadata')),
                ('docker_image', models.CharField(help_text='Docker image used for processing', max_length=200)),
                ('docker_command', models.JSONField(default=list, help_text='Docker command arguments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('error_logs', models.TextField(blank=True, help_text='Error logs if processing failed')),
                ('worker_id', models.CharField(blank=True, help_text='ID of worker processing this job', max_length=100)),
                ('scanpair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='scans.scanpair')),
                ('voice_caption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='scans.voicecaption')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('cbct_raw', 'CBCT Raw'), ('cbct_processed', 'CBCT Processed'), ('ios_raw_upper', 'IOS Raw Upper'), ('ios_raw_lower', 'IOS Raw Lower'), ('ios_processed_upper', 'IOS Processed Upper'), ('ios_processed_lower', 'IOS Processed Lower'), ('audio_raw', 'Audio Raw'), ('audio_processed', 'Audio Processed Text')], max_length=20)),
                ('file_path', models.CharField(help_text='Full path to file', max_length=500, unique=True)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_hash', models.CharField(help_text='SHA256 hash of file', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional file metadata')),
                ('scanpair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='scans.scanpair')),
                ('voice_caption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='scans.voicecaption')),
                ('processing_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='scans.processingjob')),
            ],
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['job_type', 'status'], name='scans_proce_job_typ_0a4f26_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['status', 'created_at'], name='scans_proce_status_470d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='fileregistry',
            index=models.Index(fields=['file_type', 'scanpair'], name='scans_filer_file_ty_42be0a_idx'),
        ),
        migrations.AddIndex(
            model_name='fileregistry',
            index=models.Index(fields=['file_path'], name='scans_filer_file_pa_856bfb_idx'),
        ),
    ]
