# Generated by Django 5.2.4 on 2025-07-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0010_add_processing_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicecaption',
            name='audio_file',
        ),
    ]
