# Generated by Django 5.2.4 on 2025-08-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0013_update_cbct_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='midline',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('centered', 'Centered'), ('deviated', 'Deviated')], max_length=10),
        ),
        migrations.AlterField(
            model_name='classification',
            name='sagittal_left',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('I', 'Class I'), ('II_edge', 'Class II Edge'), ('II_full', 'Class II Full'), ('III', 'Class III')], max_length=10),
        ),
        migrations.AlterField(
            model_name='classification',
            name='sagittal_right',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('I', 'Class I'), ('II_edge', 'Class II Edge'), ('II_full', 'Class II Full'), ('III', 'Class III')], max_length=10),
        ),
        migrations.AlterField(
            model_name='classification',
            name='transverse',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('normal', 'Normal'), ('cross', 'Cross Bite'), ('scissor', 'Scissor Bite')], max_length=10),
        ),
        migrations.AlterField(
            model_name='classification',
            name='vertical',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('normal', 'Normal'), ('deep', 'Deep Bite'), ('reverse', 'Reverse Bite'), ('open', 'Open Bite')], max_length=10),
        ),
    ]
