# Generated by Django 5.2.4 on 2025-08-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0014_alter_classification_midline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='dependencies',
            field=models.ManyToManyField(blank=True, help_text='Jobs that must complete before this job can start', related_name='dependent_jobs', to='scans.processingjob'),
        ),
        migrations.AlterField(
            model_name='fileregistry',
            name='file_type',
            field=models.CharField(choices=[('cbct_raw', 'CBCT Raw'), ('cbct_processed', 'CBCT Processed'), ('ios_raw_upper', 'IOS Raw Upper'), ('ios_raw_lower', 'IOS Raw Lower'), ('ios_processed_upper', 'IOS Processed Upper'), ('ios_processed_lower', 'IOS Processed Lower'), ('audio_raw', 'Audio Raw'), ('audio_processed', 'Audio Processed Text'), ('bite_classification', 'Bite Classification Results')], max_length=20),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='job_type',
            field=models.CharField(choices=[('cbct', 'CBCT Processing'), ('ios', 'IOS Processing'), ('audio', 'Audio Speech-to-Text'), ('bite_classification', 'Bite Classification')], max_length=20),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dependency', 'Waiting for Dependencies'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20),
        ),
    ]
