# Generated by Django 5.2.4 on 2025-08-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0015_processingjob_dependencies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('standard', 'Standard User'), ('annotator', 'Annotator'), ('admin', 'Administrator'), ('student_dev', 'Student Developer')], default='standard', max_length=15),
        ),
        migrations.AlterField(
            model_name='scanpair',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('debug', 'Debug')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('standard', 'Standard User'), ('annotator', 'Annotator'), ('admin', 'Administrator'), ('student_dev', 'Student Developer')], default='standard', max_length=15),
        ),
    ]
