# Generated by Django 5.2.4 on 2025-08-27 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0017_tag_folder_scanpair_folder_scanpair_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanpair',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['scanpair', 'classifier'], name='scans_class_scanpai_c0bd62_idx'),
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['classifier'], name='scans_class_classif_fc1966_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['parent'], name='scans_folde_parent__9b2827_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['name'], name='scans_folde_name_7a86ed_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['patient_id'], name='scans_patie_patient_8f4e41_idx'),
        ),
        migrations.AddIndex(
            model_name='scanpair',
            index=models.Index(fields=['visibility'], name='scans_scanp_visibil_eca196_idx'),
        ),
        migrations.AddIndex(
            model_name='scanpair',
            index=models.Index(fields=['uploaded_at'], name='scans_scanp_uploade_93256d_idx'),
        ),
        migrations.AddIndex(
            model_name='scanpair',
            index=models.Index(fields=['folder'], name='scans_scanp_folder__84b949_idx'),
        ),
        migrations.AddIndex(
            model_name='scanpair',
            index=models.Index(fields=['name'], name='scans_scanp_name_617dff_idx'),
        ),
        migrations.AddIndex(
            model_name='scanpair',
            index=models.Index(fields=['visibility', 'uploaded_at'], name='scans_scanp_visibil_1901c0_idx'),
        ),
        migrations.AddIndex(
            model_name='scanpair',
            index=models.Index(fields=['folder', 'visibility'], name='scans_scanp_folder__c964d8_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='scans_tag_name_d48e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecaption',
            index=models.Index(fields=['scanpair', 'processing_status'], name='scans_voice_scanpai_1b7374_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecaption',
            index=models.Index(fields=['processing_status'], name='scans_voice_process_cea49d_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecaption',
            index=models.Index(fields=['user'], name='scans_voice_user_id_d7afd5_idx'),
        ),
    ]
