# Generated by Django 5.2.4 on 2025-08-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0018_alter_scanpair_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicecaption',
            name='edit_history',
            field=models.JSONField(blank=True, default=list, help_text='History of edits with timestamps and users'),
        ),
        migrations.AddField(
            model_name='voicecaption',
            name='is_edited',
            field=models.BooleanField(default=False, help_text='Whether the transcription has been manually edited'),
        ),
        migrations.AddField(
            model_name='voicecaption',
            name='original_text_caption',
            field=models.TextField(blank=True, help_text='Original transcription before any edits', null=True),
        ),
    ]
