"""
Django settings for toothfairy project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY: No default secret key - must be provided via environment variable
SECRET_KEY = config("SECRET_KEY", default=None)
if not SECRET_KEY:
    raise ValueError("SECRET_KEY environment variable must be set for security reasons")

# SECURITY WARNING: don't run with debug turned on in production!
# SECURITY: Debug disabled by default for security
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost,127.0.0.1", cast=str).split(
    ","
)

# Environment-aware SSL settings
ENABLE_SSL = config("ENABLE_SSL", default=False, cast=bool)
ENABLE_HTTPS_REDIRECT = config("ENABLE_HTTPS_REDIRECT", default=False, cast=bool)
FORCE_HTTPS = config("FORCE_HTTPS", default=False, cast=bool)

# Disable HTTPS redirect in development (DEBUG mode)
# HTTPS can be handled by reverse proxy (e.g., nginx) via proxy-net
if ENABLE_SSL and not DEBUG:
    # HTTPS settings - enforce HTTPS everywhere (production only)
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = ENABLE_HTTPS_REDIRECT or FORCE_HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    # Development mode: no HTTPS redirect, allow HTTP
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    # Still set proxy header for reverse proxy scenarios, but don't enforce redirect
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "common",
    "maxillo",
    "brain",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "toothfairy.middleware.RequestLoggingMiddleware",
    "toothfairy.middleware.ProjectSessionMiddleware",
    "toothfairy.middleware.ActiveProfileMiddleware",
]

ROOT_URLCONF = "toothfairy.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "common.context_processors.current_project",
            ],
        },
    },
]

WSGI_APPLICATION = "toothfairy.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SECURITY: Database credentials must be provided via environment variables
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": config("DB_NAME", default=None),
        "USER": config("DB_USER", default=None),
        "PASSWORD": config("DB_PASSWORD", default=None),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="3306"),
        "OPTIONS": {},
    }
}

# Validate required database credentials
if not DATABASES["default"]["NAME"]:
    raise ValueError("DB_NAME environment variable must be set")
if not DATABASES["default"]["USER"]:
    raise ValueError("DB_USER environment variable must be set")
if not DATABASES["default"]["PASSWORD"]:
    raise ValueError("DB_PASSWORD environment variable must be set")

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Media files (uploaded files)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "storage"

# File Upload Settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 1048576000 * 5  # 5GB
FILE_UPLOAD_MAX_MEMORY_SIZE = 1048576000 * 5  # 5GB
DATA_UPLOAD_MAX_NUMBER_FILES = 1500  # large DICOM folder uploads


if ENABLE_SSL:
    CORS_ALLOWED_ORIGINS = [
        "https://toothfairy4m.ing.unimore.it",
        "https://localhost:8000",
        "https://127.0.0.1:8000",
    ]
else:
    CORS_ALLOWED_ORIGINS = config(
        "CORS_ALLOWED_ORIGINS",
        default="http://localhost:8000,http://127.0.0.1:8000",
        cast=str,
    ).split(",")

CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default="https://toothfairy4m.ing.unimore.it,http://localhost:8000,http://127.0.0.1:8000",
    cast=str,
).split(",")

# SECURITY: Enhanced CSRF and Session Security
CSRF_USE_SESSIONS = True  # Store CSRF token in session for better security
CSRF_COOKIE_HTTPONLY = True  # Prevent XSS attacks on CSRF cookie
CSRF_COOKIE_SAMESITE = "Strict"  # Prevent CSRF attacks
SESSION_COOKIE_HTTPONLY = True  # Prevent XSS attacks on session cookie
SESSION_COOKIE_SAMESITE = "Strict"  # Prevent session fixation attacks

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Login URLs
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Email settings
EMAIL_BACKEND = config("EMAIL_BACKEND")
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT", cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", cast=bool)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")

# Dataset path configuration
DATASET_PATH = config("DATASET_PATH", default="/dataset")

# Object storage (S3-compatible, e.g. Garage)
OBJECT_STORAGE_ENDPOINT_URL = config(
    "OBJECT_STORAGE_ENDPOINT_URL", default="http://garage:3900"
)
OBJECT_STORAGE_REGION = config("OBJECT_STORAGE_REGION", default="")
OBJECT_STORAGE_ACCESS_KEY_ID = config(
    "OBJECT_STORAGE_ACCESS_KEY_ID", default="garage-access-key"
)
OBJECT_STORAGE_SECRET_ACCESS_KEY = config(
    "OBJECT_STORAGE_SECRET_ACCESS_KEY", default="garage-secret-key"
)
OBJECT_STORAGE_BUCKET = config("OBJECT_STORAGE_BUCKET", default="toothfairy4m")
OBJECT_STORAGE_USE_SSL = config("OBJECT_STORAGE_USE_SSL", default=False, cast=bool)
OBJECT_STORAGE_VERIFY_SSL = config("OBJECT_STORAGE_VERIFY_SSL", default=True, cast=bool)
OBJECT_STORAGE_ADDRESSING_STYLE = config(
    "OBJECT_STORAGE_ADDRESSING_STYLE", default="path"
)
OBJECT_STORAGE_KEY_PREFIX = config("OBJECT_STORAGE_KEY_PREFIX", default="")

# Logging Configuration
LOG_LEVEL = config("LOG_LEVEL", default="DEBUG" if DEBUG else "INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
        "detailed": {
            "format": "[{asctime}] {levelname} {name} {funcName}:{lineno} - {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "detailed",
            "level": LOG_LEVEL,
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "logs" / "django.log",
            "formatter": "detailed",
            "level": LOG_LEVEL,
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "maxillo": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "toothfairy": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        # Add specific logger for the middleware
        "toothfairy.middleware": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
}

# In production, ensure we capture all errors
if not DEBUG:
    LOGGING["loggers"]["django"]["level"] = "WARNING"
    LOGGING["loggers"]["django.request"]["level"] = "ERROR"
    LOGGING["loggers"]["django.server"]["level"] = "ERROR"
    # But keep our app logs at DEBUG level
    LOGGING["loggers"]["maxillo"]["level"] = "DEBUG"
    LOGGING["loggers"]["toothfairy"]["level"] = "DEBUG"
    LOGGING["loggers"]["toothfairy.middleware"]["level"] = "DEBUG"

os.makedirs(BASE_DIR / "logs", exist_ok=True)
